version: "3.7"

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  mongo-data:
